-- Migration 0019: OCCI National Sacramental Records (NSR)
-- Creates all 7 NSR tables. Safe to run on existing installs (IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS `occi_parishes` (
  `id`               INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `name`             VARCHAR(255) NOT NULL,
  `city`             VARCHAR(100) NOT NULL,
  `state`            VARCHAR(100) NOT NULL,
  `cert_template_url` VARCHAR(512) DEFAULT NULL,
  `created_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `occi_baptisms` (
  `id`                   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `baptism_date`         DATE NOT NULL,
  `birth_date`           DATE DEFAULT NULL,
  `birth_place`          VARCHAR(255) DEFAULT NULL,
  `first_name`           VARCHAR(100) NOT NULL,
  `middle_name`          VARCHAR(100) DEFAULT NULL,
  `last_name`            VARCHAR(100) NOT NULL,
  `father_first_name`    VARCHAR(100) DEFAULT NULL,
  `father_middle_name`   VARCHAR(100) DEFAULT NULL,
  `father_last_name`     VARCHAR(100) DEFAULT NULL,
  `mother_first_name`    VARCHAR(100) DEFAULT NULL,
  `mother_middle_name`   VARCHAR(100) DEFAULT NULL,
  `mother_last_name`     VARCHAR(100) DEFAULT NULL,
  `mother_maiden_name`   VARCHAR(100) DEFAULT NULL,
  `sponsor1_name`        VARCHAR(255) DEFAULT NULL,
  `sponsor1_gender`      ENUM('M','F','') DEFAULT '',
  `sponsor1_is_proxy`    TINYINT(1) NOT NULL DEFAULT 0,
  `sponsor1_proxy_for`   VARCHAR(255) DEFAULT NULL,
  `sponsor2_name`        VARCHAR(255) DEFAULT NULL,
  `sponsor2_gender`      ENUM('M','F','') DEFAULT '',
  `sponsor2_is_proxy`    TINYINT(1) NOT NULL DEFAULT 0,
  `sponsor2_proxy_for`   VARCHAR(255) DEFAULT NULL,
  `minister_name`        VARCHAR(255) DEFAULT NULL,
  `minister_type`        VARCHAR(100) DEFAULT NULL,
  `parish_id`            INT UNSIGNED DEFAULT NULL,
  `alt_location`         VARCHAR(255) DEFAULT NULL,
  `notations`            TEXT DEFAULT NULL,
  `is_confidential`      TINYINT(1) NOT NULL DEFAULT 0,
  `record_book`          VARCHAR(100) DEFAULT NULL,
  `page_number`          VARCHAR(50) DEFAULT NULL,
  `created_at`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by`           INT UNSIGNED DEFAULT NULL,
  KEY `idx_last_name`  (`last_name`),
  KEY `idx_parish_id`  (`parish_id`),
  KEY `idx_baptism_date` (`baptism_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `occi_confirmations` (
  `id`                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `confirmation_date` DATE NOT NULL,
  `bishop_name`       VARCHAR(255) NOT NULL,
  `first_name`        VARCHAR(100) NOT NULL,
  `middle_name`       VARCHAR(100) DEFAULT NULL,
  `last_name`         VARCHAR(100) NOT NULL,
  `saints_name`       VARCHAR(100) DEFAULT NULL,
  `parish_id`         INT UNSIGNED DEFAULT NULL,
  `alt_location`      VARCHAR(255) DEFAULT NULL,
  `notations`         TEXT DEFAULT NULL,
  `created_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_last_name`         (`last_name`),
  KEY `idx_parish_id`         (`parish_id`),
  KEY `idx_confirmation_date` (`confirmation_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `occi_marriages` (
  `id`                   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `marriage_date`        DATE NOT NULL,
  `party1_first_name`    VARCHAR(100) NOT NULL,
  `party1_middle_name`   VARCHAR(100) DEFAULT NULL,
  `party1_last_name`     VARCHAR(100) NOT NULL,
  `party1_maiden_name`   VARCHAR(100) DEFAULT NULL,
  `party1_birth_date`    DATE DEFAULT NULL,
  `party2_first_name`    VARCHAR(100) NOT NULL,
  `party2_middle_name`   VARCHAR(100) DEFAULT NULL,
  `party2_last_name`     VARCHAR(100) NOT NULL,
  `party2_maiden_name`   VARCHAR(100) DEFAULT NULL,
  `party2_birth_date`    DATE DEFAULT NULL,
  `witness1_name`        VARCHAR(255) NOT NULL,
  `witness2_name`        VARCHAR(255) NOT NULL,
  `minister_name`        VARCHAR(255) NOT NULL,
  `parish_id`            INT UNSIGNED DEFAULT NULL,
  `alt_location`         VARCHAR(255) DEFAULT NULL,
  `notations`            TEXT DEFAULT NULL,
  `created_at`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by`           INT UNSIGNED DEFAULT NULL,
  KEY `idx_party1_last`   (`party1_last_name`),
  KEY `idx_party2_last`   (`party2_last_name`),
  KEY `idx_parish_id`     (`parish_id`),
  KEY `idx_marriage_date` (`marriage_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `occi_deaths` (
  `id`                     INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `death_date`             DATE NOT NULL,
  `first_name`             VARCHAR(100) NOT NULL,
  `middle_name`            VARCHAR(100) DEFAULT NULL,
  `last_name`              VARCHAR(100) NOT NULL,
  `burial_location`        VARCHAR(255) DEFAULT NULL,
  `burial_city`            VARCHAR(100) DEFAULT NULL,
  `burial_state`           VARCHAR(100) DEFAULT NULL,
  `funeral_date`           DATE DEFAULT NULL,
  `funeral_presider`       VARCHAR(255) DEFAULT NULL,
  `parish_id`              INT UNSIGNED DEFAULT NULL,
  `is_graveside`           TINYINT(1) NOT NULL DEFAULT 0,
  `cemetery_name`          VARCHAR(255) DEFAULT NULL,
  `cemetery_city`          VARCHAR(100) DEFAULT NULL,
  `cemetery_state`         VARCHAR(100) DEFAULT NULL,
  `is_cremated`            TINYINT(1) NOT NULL DEFAULT 0,
  `ashes_interment_date`   DATE DEFAULT NULL,
  `ashes_interment_place`  VARCHAR(255) DEFAULT NULL,
  `notations`              TEXT DEFAULT NULL,
  `created_at`             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_last_name`  (`last_name`),
  KEY `idx_parish_id`  (`parish_id`),
  KEY `idx_death_date` (`death_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `occi_communions` (
  `id`               INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `communion_date`   DATE NOT NULL,
  `first_name`       VARCHAR(100) NOT NULL,
  `middle_name`      VARCHAR(100) DEFAULT NULL,
  `last_name`        VARCHAR(100) NOT NULL,
  `baptism_date`     DATE DEFAULT NULL,
  `baptism_church`   VARCHAR(255) DEFAULT NULL,
  `baptism_city`     VARCHAR(100) DEFAULT NULL,
  `baptism_state`    VARCHAR(100) DEFAULT NULL,
  `presider`         VARCHAR(255) NOT NULL,
  `parish_id`        INT UNSIGNED DEFAULT NULL,
  `notations`        TEXT DEFAULT NULL,
  `created_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_last_name`      (`last_name`),
  KEY `idx_parish_id`      (`parish_id`),
  KEY `idx_communion_date` (`communion_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `occi_ordinations` (
  `id`                INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `ordination_date`   DATE NOT NULL,
  `first_name`        VARCHAR(100) NOT NULL,
  `middle_name`       VARCHAR(100) DEFAULT NULL,
  `last_name`         VARCHAR(100) NOT NULL,
  `ordination_rank`   ENUM('Deacon','Priest','Bishop') NOT NULL,
  `presiding_bishop`  VARCHAR(255) NOT NULL,
  `co_consecrator1`   VARCHAR(255) DEFAULT NULL,
  `co_consecrator2`   VARCHAR(255) DEFAULT NULL,
  `co_consecrator3`   VARCHAR(255) DEFAULT NULL,
  `parish_id`         INT UNSIGNED DEFAULT NULL,
  `alt_location`      VARCHAR(255) DEFAULT NULL,
  `notations`         TEXT DEFAULT NULL,
  `created_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY `idx_last_name`       (`last_name`),
  KEY `idx_parish_id`       (`parish_id`),
  KEY `idx_ordination_date` (`ordination_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
