-- Migration 0021: Clergy Directory

CREATE TABLE IF NOT EXISTS `clergy` (
  `id`               INT UNSIGNED  NOT NULL AUTO_INCREMENT,
  `photo`            VARCHAR(500)  DEFAULT NULL,
  `title_prefix`     VARCHAR(50)   NOT NULL DEFAULT '',
  `title_custom`     VARCHAR(100)  DEFAULT NULL,
  `first_name`       VARCHAR(100)  NOT NULL DEFAULT '',
  `last_name`        VARCHAR(100)  NOT NULL DEFAULT '',
  `religious_order`  VARCHAR(50)   DEFAULT NULL,
  `address_line1`    VARCHAR(255)  DEFAULT NULL,
  `address_line2`    VARCHAR(255)  DEFAULT NULL,
  `city`             VARCHAR(100)  DEFAULT NULL,
  `state_province`   VARCHAR(100)  DEFAULT NULL,
  `postal_code`      VARCHAR(20)   DEFAULT NULL,
  `country`          VARCHAR(100)  DEFAULT NULL,
  `phone`            VARCHAR(50)   DEFAULT NULL,
  `email`            VARCHAR(255)  DEFAULT NULL,
  `parish`           VARCHAR(255)  DEFAULT NULL,
  `diocese`          VARCHAR(255)  DEFAULT NULL,
  `office`           VARCHAR(255)  DEFAULT NULL,
  `position`         ENUM('presiding_bishop','chancellor','bishop','monsignor','priest',
                          'deacon','subdeacon','religious','seminarian','candidate','laity')
                     NOT NULL DEFAULT 'laity',
  `social_facebook`  VARCHAR(500)  DEFAULT NULL,
  `social_instagram` VARCHAR(500)  DEFAULT NULL,
  `social_twitter`   VARCHAR(500)  DEFAULT NULL,
  `social_threads`   VARCHAR(500)  DEFAULT NULL,
  `social_youtube`   VARCHAR(500)  DEFAULT NULL,
  `social_tiktok`    VARCHAR(500)  DEFAULT NULL,
  `social_linkedin`  VARCHAR(500)  DEFAULT NULL,
  `social_bluesky`   VARCHAR(500)  DEFAULT NULL,
  `social_pinterest` VARCHAR(500)  DEFAULT NULL,
  `social_snapchat`  VARCHAR(500)  DEFAULT NULL,
  `status`           ENUM('active','inactive') NOT NULL DEFAULT 'active',
  `menu_order`       SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `created_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_position`   (`position`),
  KEY `idx_status`     (`status`),
  KEY `idx_menu_order` (`menu_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
